services:
  - type: web
    name: zhenduanqi
    runtime: docker
    plan: free
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: TOKEN_SECRET
        generateValue: true
      - key: JWT_EXPIRATION_MS
        value: "7200000"
